name: ChikAutoo Android CI CD DevSecOps

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test-package:
    name: Build, Unit Tests and APK
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code source
        uses: actions/checkout@v4

      - name: Installer Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Donner permission à Gradle
        run: chmod +x ./gradlew

      - name: Compiler l'application
        run: ./gradlew assembleDebug

      - name: Lancer les tests unitaires
        run: ./gradlew testDebugUnitTest

      - name: Sauvegarder le rapport des tests
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rapport-tests-unitaires
          path: app/build/reports/tests/testDebugUnitTest/

      - name: Sauvegarder APK Debug
        uses: actions/upload-artifact@v4
        with:
          name: ChikAuto-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

  secret-detection:
    name: Secret Detection - Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scanner les secrets avec Gitleaks
        uses: gitleaks/gitleaks-action@v2

  sast-codeql:
    name: SAST - CodeQL
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Initialiser CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java-kotlin

      - name: Compiler pour CodeQL
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Analyse SAST CodeQL
        uses: github/codeql-action/analyze@v3

  sca-dependencies:
    name: SCA - Analyse dépendances
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Scanner les dépendances
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: ChikAuto
          path: .
          format: HTML

      - name: Sauvegarder rapport SCA
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rapport-sca-dependances
          path: reports/